### ISSUE TITLE
Create a homepage and push it to github

### ISSUE THREAD

**Issue by Nvd09** [UB-CSE/course-project-5braincells#10]
Create a home page with a search bar and category buttons, as well as a navigation bar at the bottom that lists other pages such as the profile page.

Task test:
1. After logging in, a user should see the homepage.
2. By clicking on the search box, a user can search any services.
3. Click on any of the suggestions under the search box to get that service.
4. Click on the navigation bar at the bottom to navigate through different screens.

**Comment by BrandonL23** [comment]
Create a home page with a search bar and category buttons, as well as a navigation bar at the bottom to redirect users to other pages such as the profile page.
