### ISSUE TITLE
Create route in server to update user image

### ISSUE THREAD

**Issue by Nvd09** [UB-CSE/course-project-5braincells#104]
Task Test :
1. Create route in server to update profilePic of user
2. The route takes in a new image source and the user id
3. It returns the user with the updated profile image with the new image source being the source for the profile pic

**Comment by yingwei123** [comment]
Task Test :
1. Create route in server to update profilePic of user
2. The route takes in a new image source and the user id
3. It returns the user with the updated profile image with the new image source being the source for the profile pic
