### ISSUE TITLE
Create Server so our flutter app can communicate with the database

### ISSUE THREAD

**Issue by yingwei123** [UB-CSE/course-project-5braincells#23]
Task Test :
1. Change to serverStuff branch on github
2. Install dependencies for server using npm install
3. Launch the server using npm start
4. Check if "Server Loaded Properly" is loaded properly in terminal
5. Check https://job-5cells.herokuapp.com/ (Hosted on heroku for errors)

**Comment by ProfMatthewHz** [comment]
Why is this in testing without a Sprint 2 label? Label work with the Sprint in which it is developed. Also, where are your task tests? How can an outside come on to the project and know where the server is and how to access it?

**Comment by yingwei123** [comment]
Task Test :
Change to serverStuff branch on github

Install dependencies for server using npm install 

Launch the server using npm start

Check if "Server Loaded Properly" is loaded properly in terminal 

Check https://job-5cells.herokuapp.com/ (Hosted on heroku for errors)

**Comment by ProfMatthewHz** [comment]
Remember you need to have an application running on live hardware at the end of this (and all the following) sprints. Where is this server running? What mobile system are you using?

**Comment by yingwei123** [comment]
I'm currently hosting the web server on heroku. Flutter works on android and macOs. Our app currently runs on an android emulator  and it will communicate with the web server using http req to update or get stuff from the database. 

our server -> (https://job-5cells.herokuapp.com/)
Theres a RestApi.md doc in serverStuff branch that explains the current routes, what they do, how to use it, and sample call/responses

**Comment by yingwei123** [comment]
Do we need to upload our app on google play store by sprint 2?

**Comment by ProfMatthewHz** [comment]
You might want to list where your server in the test.

You do not need the app to be in the Google Play Store (ever), but you will need it running on an actual phone. Emulators are not allowed for the release demo.
