### ISSUE TITLE
Create a database to save the sign up and login information

### ISSUE THREAD

**Issue by Nvd09** [UB-CSE/course-project-5braincells#29]
Task Test:
Login to https://www.mongodb.com/ using projectdatabase12345@gmail.com email

Click Cluster0

Go to Collections Tab

Make sure users is under Collections

Check to see if the users are correctly formatted

**Comment by yingwei123** [comment]
Task Test:
Login to https://www.mongodb.com/ using projectdatabase12345@gmail.com email

Click Cluster0

Go to Collections Tab

Make sure users is under Collections

Check to see if the users are correctly formatted
