### ISSUE TITLE
Create listing object in databsae so we can save the unique users listings. 

### ISSUE THREAD

**Issue by Nvd09** [UB-CSE/course-project-5braincells#40]
Task Test:
Login to https://www.mongodb.com/ using projectdatabase12345@gmail.com email

Click Cluster0

Go to Collections Tab

Make sure listings is under Collections

Check to see if the listings are correctly formatted

**Comment by yingwei123** [comment]
Task Test:
Login to https://www.mongodb.com/ using projectdatabase12345@gmail.com email

Click Cluster0

Go to Collections Tab

Make sure listings is under Collections

Check to see if the listings are correctly formatted
